### ISSUE TITLE
Issue with TCGA2Stat

### ISSUE THREAD

**Issue by talele** [mdozmorov/TCGAsurvival#1]
The line 
get_data(cancers = cancer_TCGA, data.type = data.type, type = type, data_dir = data_dir, force_reload = TRUE)
returns with error in TCGA2STAT. 

Installing TCGA2STAT was no good since current version 3.5.1 is not supported. Any work arounds?

**Comment by mdozmorov** [comment]
Do you refer to 3.5.1 version of R? I have TCGA2STAT v.1.2 running on R v.3.6.0, all works.

**Comment by talele** [comment]
Indeed, updating R to v3.6 and installing TCGA2STAT v.1.2 worked!
Thanks Mikhail!

**Comment by ksrinivasprabhu1999** [comment]
> Do you refer to 3.5.1 version of R? I have TCGA2STAT v.1.2 running on R v.3.6.0, all works.

How did you get TCGA2STAT v.1.2 ? I am not able to install it. Please help. Thanks.

**Comment by mdozmorov** [comment]
Just follow the instructions http://www.liuzlab.org/TCGA2STAT/#install-from-download-package

Download from https://github.com/zhandong/TCGA2STAT

You'll need to install `CNTools` beforehand, and it all works.

Install as `install.packages("TCGA2STAT_1.2.tar.gz", repos = NULL, type = "source")`
