### ISSUE TITLE
Need a link to download data for CellX analysis. The current link is notworking. Please help

### ISSUE THREAD

**Issue by ksrinivasprabhu1999** [mdozmorov/TCGAsurvival#12]
Go to [http://54.149.52.246/cgi-bin/RPPA/cellx.cgi](http://54.149.52.246/cgi-bin/RPPA/cellx.cgi)
- Select "Expression" tab out of "CNV"/"Expression"/"Mutation"/"Other" tabs
- Select the "RSEM-barplot" option on the sidebar. Read more about RSEM selected_gene expression measures at [https://deweylab.github.io/RSEM/](https://deweylab.github.io/RSEM/)
- Select any cancer-associated selected_gene from [http://cancer.sanger.ac.uk/census](http://cancer.sanger.ac.uk/census), e.g., "ERBB2". Alternatively, use any selected_gene name you may find biologically interesting
- Enter lower-case selected_gene name into the "HUGO" textbox at the bottom of the page
- Click "Submit" - the page will refresh in ~20 sec
- Save the tab-separated data using "Download table" link into `data/RSEM_expression_GENESYMBOL.data.tsv`
- Import the downloaded data into R.
Please help me download this file / or a link from where I can get a file to download this. 
THanks alot

**Comment by mdozmorov** [comment]
See Issue #3.
