### ISSUE TITLE
I am getting an error while running the script at this line . I have prepared the data and have TAR installed too. Please help. I really need to pull this through.

### ISSUE THREAD

**Issue by ksrinivasprabhu1999** [mdozmorov/TCGAsurvival#14]
https://github.com/mdozmorov/TCGAsurvival/blob/a2037ee35ffc17ff79de77e60de1d0fac34367c1/survival.Rmd#L85
Error in apply(mtx$clinical, 2, function(x) length(table(x[!(is.na(x) &  : 
  dim(X) must have a positive length
Thank you.

**Comment by mdozmorov** [comment]
Share the whole file, so I can try to reproduce. If the data is prepared correctly, there shouldn't be any error at this line.

**Comment by ksrinivasprabhu1999** [comment]
I am running the demo shown here, could you tell me what all data I need to store in the dir to process the code ?

**Comment by ksrinivasprabhu1999** [comment]
> I am running the demo shown here, could you tell me what all data I need to store in the dir to process the code ?

data.TCGA/EINAV_INTERFERON_SIGNATURE_IN_CANCER.txt I could not find this is in data.TCGA.
