### ISSUE TITLE
Pan-cancer over-expressed or down-regulated gene list

### ISSUE THREAD

**Issue by Shicheng-Guo** [mdozmorov/TCGAsurvival#15]
Hi Mikhail, 

Do you know which TCGA paper include a full list for over-expression pan-cancer genes? 

Thanks

Shicheng

**Comment by mdozmorov** [comment]
Hi Shicheng. I have some notes on that, PCAGW genes seem the closest you are looking for https://github.com/mdozmorov/Cancer_notes#cancer-driver-genes

Closing, but ask here if still have questions.
