### ISSUE TITLE
Cannot connect to Firehose Internet

### ISSUE THREAD

**Issue by thesimranvenkat** [mdozmorov/TCGAsurvival#16]
I can't seem to load the data in the TCGA_preprocessing script line: 
```
for (cancer_type in all_cancers) {
  print(paste0("Processing cancer ", cancer_type))
  mtx <- load_data(disease = cancer_type, data.type = data.type, type = type, data_dir = data_dir, force_reload = FALSE)
  # Prepare expression data
  expr <- mtx$merged.dat[ , 4:ncol(mtx$merged.dat)] %>% as.matrix
  cancer_counts <- rbind(cancer_counts, c(cancer_type, nrow(expr)))
}  

Error: Problem connect to Firehose. Please ensure Internet connection is working.

Error in gzfile(file, "wb") : cannot open the connection
In addition: Warning message:
In gzfile(file, "wb") :
  cannot open compressed file 'D:/Bioinformatics/data/mtx_ACC_RNASeq2_.rda', probable reason 'No such file or directory'
```

I'm currently running this on R.4.0.2 on a windows system and have no options to switch over to another OS at the moment.

**Comment by mdozmorov** [comment]
Hi @thesimranvenkat, the Firehose has been decommissioned. As well as the TCGA2STAT package. The error is the same on my end, if I try to redownload (`force = TRUE`) the data. I would recommend the [curatedTCGAData](https://bioconductor.org/packages/curatedTCGAData/) and [TCGAutils](https://bioconductor.org/packages/TCGAutils/) packages. 

If you would still like to use my scripts, I uploaded the data I have downloaded previously [here](https://drive.google.com/drive/folders/1rUpbpXtvglUzgXGzzCMAvt8C0Wp3ntCp?usp=share_link). You need to download it on your computer and adjust the `data_dir` variable.

**Comment by thesimranvenkat** [comment]
Thank you so much for this. Just wanted to confirm, despite TCGA2STAT  being decommissioned, the survival related scripts would still work? I can still run the Analysis 2 chunk?

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by mdozmorov** [comment]
Yes, all analyses should work and be accurate.
