### ISSUE TITLE
cannot access http://54.149.52.246/cgi-bin/RPPA/cellx.cgi

### ISSUE THREAD

**Issue by malinimanoharan** [mdozmorov/TCGAsurvival#3]
I am unable to access the cellx data in the above URL.

**Comment by mdozmorov** [comment]
Yes, it seems inaccessible. The project page is https://sourceforge.net/projects/cellx/, but the link to the web site times out. Asking Keith, @killerz99, the creator of CELLX, for help.

**Comment by killerz99** [comment]
Hi, sorry I took down the CELLX site recently.. not planning to support it further.. didn't realize there were dependencies.  The data and code are deprecated.. there is new survival data published, so its best to go with the new version.  The local install instructions should still work and the data should be available in the repository, so you could recreate the parts that you need if you have to.

**Comment by mdozmorov** [comment]
Thanks, Keith, no problem, everything has its lifetime. @malinimanoharan, you likely saw that my scripts use local TCGA data. If you can make a pull request for CELLX_analysis.Rmd to make use of those, that'll be great. Otherwise, I'll try to get to it.

**Comment by ksrinivasprabhu1999** [comment]
Hi could someone please fix this ? thanks.

**Comment by ksrinivasprabhu1999** [comment]
> Hi, sorry I took down the CELLX site recently.. not planning to support it further.. didn't realize there were dependencies. The data and code are deprecated.. there is new survival data published, so its best to go with the new version. The local install instructions should still work and the data should be available in the repository, so you could recreate the parts that you need if you have to.

HI could you please give a link to where I can download the data for this analysis ?
Thanks a lot.

**Comment by mdozmorov** [comment]
See [tnmplot.com/](https://tnmplot.com/) - differential gene expression analysis in Tumor, Normal and Metastatic tissues. Bartha, Áron, and Balázs Győrffy. “[TNMplot.Com: A Web Tool for the Comparison of Gene Expression in Normal, Tumor and Metastatic Tissues](https://doi.org/10.1101/2020.11.10.376228)”
