### ISSUE TITLE
TCGA_expression.rmd

### ISSUE THREAD

**Issue by ksrinivasprabhu1999** [mdozmorov/TCGAsurvival#4]
This is while running the TCGA_expression.rmd.
Error in names(object) <- nm :
'names' attribute [1] must be the same length as the vector [0]
Hi, Firstly thanks a lot for sharing this work. It was a great help. Also I am getting this above error. Could you please help me sort it out ?
Thanks again.

**Comment by ksrinivasprabhu1999** [comment]
This is while running the TCGA_expression.rmd.
Error in names(object) <- nm : 
  'names' attribute [1] must be the same length as the vector [0]
Hi, Firstly thanks a lot for sharing this work. It was a great help. Also I am getting this above error. Could you please help me sort it out ?
Thanks again.

**Comment by mdozmorov** [comment]
The code works on my end. Make sure you use canonical gene names. Make sure expression data for all cancers are downloaded, see "Data preprocessing" in the README. Try selecting just one cancer, line 134, like `cancer_RNASeq2 = c("BRCA"))`.
