### ISSUE TITLE
Stuck. Need help.

### ISSUE THREAD

**Issue by ksrinivasprabhu1999** [mdozmorov/TCGAsurvival#5]
I am extremely interested in trying to work this out but I am stuck. I am new to coding and hence would need your help. I am getting tons of errors and I tried everything but I am unable to move further. ( TCGA_expression.Rmd )
Could you maybe show me 1 case for full analysis ( only the TCGA expression.rmd part )starting from data downloading to output?
Forever grateful thanks.
Regards,
Prabhu.

**Comment by mdozmorov** [comment]
All steps are described in the [README](https://github.com/mdozmorov/TCGAsurvival). I'm not sure what errors you are getting. Depending on your goals, you may try Bioconductor ecosystem, https://bioconductor.org/packages/release/data/experiment/html/curatedTCGAData.html
