### ISSUE TITLE
TCGA misc/TCGA_datapreprocessing script

### ISSUE THREAD

**Issue by ksrinivasprabhu1999** [mdozmorov/TCGAsurvival#7]
Error in apply(mtx$clinical, 2, function(x) length(table(x[!(is.na(x) &  : 
  dim(X) must have a positive length.
How can I fix this ?

**Comment by mdozmorov** [comment]
I need exact code that reproduces the error.

**Comment by ksrinivasprabhu1999** [comment]
Code  - 
library(TCGA2STAT)
library(dplyr)
library(knitr)
data_dir = "E:/Data/GenomeRunner/TCGAsurvival/data"
results_dir = data_dir
data.type = "RNASeq2"
type = "" 
data.type = "miRNASeq" # miRNASeq - "count" for raw read counts (default); "rpmmm" for normalized read counts
type = "rpmmm"
data.type = "Mutation"
type = "somatic"
type="all"
data.type = "Methylation"
type = "450K"
clinical = TRUE
# Breast cancer
cancer = "BRCA" 
# Ovarian cancer
cancer = "OV"
# Liver hepatocellular carcinoma
cancer = "LIHC" 
# Head and Neck squamous cell carcinoma
cancer = "HNSC" 
# Sarcoma
cancer = "SARC" 
# Pancreatic cancer
cancer = "PAAD" 
# Lung adenocarcinoma
cancer = "LUAD"
# Lung squamous cell carcinoma
cancer = "LUSC"
# A function to load TCGA data, from remote repository, or a local R object
load_data <- function(disease = cancer, data.type = data.type, type = type, data_dir = data_dir, force_reload = FALSE) {
  FILE = paste0(data_dir, "/mtx_", disease, "_", data.type, "_", type, ".rda") # R object with data
  if (all(file.exists(FILE), !(force_reload))) {
    # If the data has been previously saved, load it
    load(file = FILE)
  } else {
    # If no saved data exists, get it from the remote source
    mtx <- getTCGA(disease = disease, data.type = data.type, type = type, clinical = TRUE)
    save(file = FILE, list = c("mtx")) # Save it
  }
  return(mtx)
}
summarize_data <- function(mtx = mtx) {
  print(paste0("Dimensions of expression matrix, genex X patients: ", paste(dim(mtx$dat), collapse = " ")))
  print(paste0("Dimensions of clinical matrix, patients X parameters: ", paste(dim(mtx$clinical), collapse = " ")))
  print(paste0("Dimensions of merged matrix, patients X parameters + genes: ", paste(dim(mtx$merged.dat), collapse = " ")))
  print("Head of the merged matrix")
  print(mtx$merged.dat[1:5, 1:10])
  print("Head of the clinical matrix")
  print(mtx$clinical[1:5, 1:7])
  print("List of clinical values, and frequency of each variable: ")
  clin_vars <- apply(mtx$clinical, 2, function(x) length(table(x[ !(is.na(x) & x != "" )]))) %>% as.data.frame()
  # Filter clinical variables to have at least 2, but no more than 10 categories,
  # And they are not dates
  clin_vars <- clin_vars[ as.numeric(clin_vars$.) > 1 & as.numeric(clin_vars$.) < 10 & !grepl("years|days|date|vital", rownames(clin_vars), perl = TRUE) , , drop = FALSE]
  print(kable(clin_vars))
  return(rownames(clin_vars))
}
make_expression_matrix <- function(mtx = mtx, disease = cancer, data.type = data.type, type = type, results_dir = results_dir) {
  # transposed expression matrix (genes start at column 4) 
  mtx.expression <- mtx$merged.dat[, 4:ncol(mtx$merged.dat) ] %>% t 
  # Set column names as patient IDs
  colnames(mtx.expression) <- mtx$merged.dat$bcr 
  # Set row names as probe IDs
  rownames(mtx.expression) <- colnames(mtx$merged.dat)[ 4:ncol(mtx$merged.dat) ] 
  # Save gzipped matrix
  fileName.gz <- gzfile(paste0(results_dir, "/mtx_", disease, "_", data.type, "_", type, "_1expression.txt.gz"), "w")
  write.table(mtx.expression, fileName.gz, sep = ";", quote = FALSE)
  close(fileName.gz)
}
make_mapping_matrix <- function(mtx = mtx, disease = cancer, data.type = data.type, type = type, results_dir = results_dir) {
  mtx.mapping <- data.frame(probeID = colnames(mtx$merged.dat)[ 4:ncol(mtx$merged.dat) ],
                            geneID = colnames(mtx$merged.dat)[ 4:ncol(mtx$merged.dat) ])
  # Save gzipped matrix
  fileName.gz <- gzfile(paste0(results_dir, "/mtx_", disease, "_", data.type, "_", type, "_2mapping.txt.gz"), "w")
  write.table(mtx.mapping, fileName.gz, sep = ";", quote = FALSE, col.names = FALSE, row.names = FALSE)
  close(fileName.gz)
}
make_annotation_matrix <- function(mtx = mtx, disease = cancer, data.type = data.type, type = type, clinical_annotations = clinical_annotations, results_dir = results_dir) {
  mtx.sample <- mtx$merged.dat[, c("bcr", "OS", "status")] # First 3 columns are c("sample_id", "surv_time", "dead_1_alive_0")
  colnames(mtx.sample) <- c("sample_id", "surv_time", "dead_1_alive_0")
  # Append selected clinical annotations
  mtx.sample <- left_join(mtx.sample, data.frame(sample_id = rownames(mtx$clinical), mtx$clinical[, colnames(mtx$clinical) %in% clinical_annotations], stringsAsFactors = FALSE), by = "sample_id")
  mtx.sample[ is.na(mtx.sample) ] <- "N/A"
  mtx.sample <- mtx.sample[, apply(mtx.sample, 2, function(x) length(x[ x != "N/A"])) > 40] # Keep clinical annitations with at least 40 patients
  # Save gzipped matrix
  fileName.gz <- gzfile(paste0(results_dir, "/mtx_", disease, "_", data.type, "_", type, "_3sample.txt.gz"), "w")
  write.table(mtx.sample, fileName.gz, sep = ";", quote = FALSE, row.names = FALSE)
  close(fileName.gz)
}
# mtx <- load_data(disease = cancer, data.type = data.type, type = type, data_dir = data_dir, force_reload = FALSE)

# clinical_annotations <- summarize_data(mtx = mtx)

# make_expression_matrix(mtx = mtx, disease = cancer, data.type = data.type, type = type, results_dir = results_dir)

# make_mapping_matrix(mtx = mtx, disease = cancer, data.type = data.type, type = type, results_dir = results_dir)

# make_annotation_matrix(mtx = mtx, disease = cancer, data.type = data.type, type = type, clinical_annotations = clinical_annotations, results_dir = results_dir)

# Get data for all cancers
get_data <- function(cancers, data.type = data.type, type = type, data_dir = data_dir, force_reload) {
  for (cancer in cancers) {
    print(paste0("Processing cancer ", cancer))
    mtx <- load_data(disease = cancer, data.type = data.type, type = type, data_dir = data_dir, force_reload)
    clinical_annotations <- summarize_data(mtx = mtx)
    make_expression_matrix(mtx = mtx, disease = cancer, data.type = data.type, type = type, results_dir = results_dir)
    make_mapping_matrix(mtx = mtx, disease = cancer, data.type = data.type, type = type, results_dir = results_dir)
    make_annotation_matrix(mtx = mtx, disease = cancer, data.type = data.type, type = type, clinical_annotations = clinical_annotations, results_dir = results_dir)
    rm(list = c("mtx", "clinical_annotations"))
  }
}

# All cancers with RNASeq2 data
data.type = "RNASeq2"; type = "" 
cancer_TCGA = c("ACC", "BLCA", "BRCA", "CESC", "CHOL", "COAD", "COADREAD", "DLBC", "ESCA", "GBM", "GBMLGG", "HNSC", "KICH", "KIPAN", "KIRC", "KIRP", "LAML", "LGG", "LIHC", "LUAD", "LUSC", "MESO", "OV", "PAAD", "PCPG", "PRAD", "READ", "SARC", "SKCM", "STAD", "TGCT", "THCA", "THYM", "UCEC", "UCS")
# All cancers with miRNAseq data. Uncomment to get miRNAseq data
# data.type = "miRNASeq"; type = "rpmmm"
# cancer_TCGA = c("ACC", "BLCA", "BRCA", "CESC", "CHOL", "COAD", "COADREAD", "DLBC", "ESCA", "GBM", "GBMLGG", "HNSC", "KICH", "KIPAN", "KIRC", "KIRP", "LGG", "LIHC", "LUAD", "LUSC", "MESO", "OV", "PAAD", "PCPG", "PRAD", "READ", "SARC", "SKCM", "STAD", "TGCT", "THCA", "THYM", "UCEC", "UCS") # "LAML"

# sink("TCGA2SynTarget.txt", split = FALSE)
get_data(cancers = cancer_TCGA, data.type = data.type, type = type, data_dir = data_dir, force_reload = TRUE)
# sink(type = "message")
# sink()

# Cleanup intermediate files
unlink(paste0(data_dir, "/*.txt.gz"))

# Get number of subjects for all cancers
# All cancers
all_cancers = c("ACC", "BLCA", "BRCA", "CESC", "CHOL", "COAD", "COADREAD", "DLBC", "ESCA", "GBM", "HNSC", "KICH", "KIPAN", "KIRC", "KIRP", "LIHC", "LUAD", "LUSC", "MESO", "OV", "PAAD", "PCPG", "PRAD", "READ", "SARC", "SKCM", "STAD", "TGCT", "THCA", "THYM", "UCEC", "UCS", "GBMLGG", "LGG")
data.type = "RNASeq2"; type = "" 
cancer_counts = rbind()
for (cancer_type in all_cancers) {
  print(paste0("Processing cancer ", cancer_type))
  mtx <- load_data(disease = cancer_type, data.type = data.type, type = type, data_dir = data_dir, force_reload = FALSE)
  # Prepare expression data
  expr <- mtx$merged.dat[ , 4:ncol(mtx$merged.dat)] %>% as.matrix
  cancer_counts <- rbind(cancer_counts, c(cancer_type, nrow(expr)))
}  
cancer_counts <- data.frame(Cancer = cancer_counts[, 1], Samples = as.numeric(cancer_counts[, 2]))
cancer_counts <- cancer_counts[order(cancer_counts$Samples, decreasing = TRUE), ]
write.table(cancer_counts, "data.TCGA/TCGA_cancer_counts.csv", sep = ",", row.names = FALSE, quote = FALSE)

Error
In the console 
> source('~/.active-rstudio-document')
> source('E:/DATA/GenomeRunner/TCGAsurvival/data/Data_Preprocessing.R')
[1] "Processing cancer ACC"
Error: TAR is not installed in the system. Data unzip failed.

[1] "Dimensions of expression matrix, genex X patients: "
[1] "Dimensions of clinical matrix, patients X parameters: "
[1] "Dimensions of merged matrix, patients X parameters + genes: "
[1] "Head of the merged matrix"
NULL
[1] "Head of the clinical matrix"
NULL
[1] "List of clinical values, and frequency of each variable: "
Error in apply(mtx$clinical, 2, function(x) length(table(x[!(is.na(x) &  : 
  dim(X) must have a positive length
Called from: apply(mtx$clinical, 2, function(x) length(table(x[!(is.na(x) & 
    x != "")])))
Browse[1]> 
Please let me know if you need any more information. Thanks.

**Comment by ksrinivasprabhu1999** [comment]
library(TCGA2STAT)
library(dplyr)
library(knitr)
data_dir = "E:/Data/GenomeRunner/TCGAsurvival/data"
results_dir = data_dir
data.type = "RNASeq2"
type = "" 
data.type = "miRNASeq" # miRNASeq - "count" for raw read counts (default); "rpmmm" for normalized read counts
type = "rpmmm"
data.type = "Mutation"
type = "somatic"
type="all"
data.type = "Methylation"
type = "450K"
clinical = TRUE
# Breast cancer
cancer = "BRCA" 
# Ovarian cancer
cancer = "OV"
# Liver hepatocellular carcinoma
cancer = "LIHC" 
# Head and Neck squamous cell carcinoma
cancer = "HNSC" 
# Sarcoma
cancer = "SARC" 
# Pancreatic cancer
cancer = "PAAD" 
# Lung adenocarcinoma
cancer = "LUAD"
# Lung squamous cell carcinoma
cancer = "LUSC"
# A function to load TCGA data, from remote repository, or a local R object
load_data <- function(disease = cancer, data.type = data.type, type = type, data_dir = data_dir, force_reload = FALSE) {
  FILE = paste0(data_dir, "/mtx_", disease, "_", data.type, "_", type, ".rda") # R object with data
  if (all(file.exists(FILE), !(force_reload))) {
    # If the data has been previously saved, load it
    load(file = FILE)
  } else {
    # If no saved data exists, get it from the remote source
    mtx <- getTCGA(disease = disease, data.type = data.type, type = type, clinical = TRUE)
    save(file = FILE, list = c("mtx")) # Save it
  }
  return(mtx)
}
summarize_data <- function(mtx = mtx) {
  print(paste0("Dimensions of expression matrix, genex X patients: ", paste(dim(mtx$dat), collapse = " ")))
  print(paste0("Dimensions of clinical matrix, patients X parameters: ", paste(dim(mtx$clinical), collapse = " ")))
  print(paste0("Dimensions of merged matrix, patients X parameters + genes: ", paste(dim(mtx$merged.dat), collapse = " ")))
  print("Head of the merged matrix")
  print(mtx$merged.dat[1:5, 1:10])
  print("Head of the clinical matrix")
  print(mtx$clinical[1:5, 1:7])
  print("List of clinical values, and frequency of each variable: ")
  clin_vars <- apply(mtx$clinical, 2, function(x) length(table(x[ !(is.na(x) & x != "" )]))) %>% as.data.frame()
  # Filter clinical variables to have at least 2, but no more than 10 categories,
  # And they are not dates
  clin_vars <- clin_vars[ as.numeric(clin_vars$.) > 1 & as.numeric(clin_vars$.) < 10 & !grepl("years|days|date|vital", rownames(clin_vars), perl = TRUE) , , drop = FALSE]
  print(kable(clin_vars))
  return(rownames(clin_vars))
}
make_expression_matrix <- function(mtx = mtx, disease = cancer, data.type = data.type, type = type, results_dir = results_dir) {
  # transposed expression matrix (genes start at column 4) 
  mtx.expression <- mtx$merged.dat[, 4:ncol(mtx$merged.dat) ] %>% t 
  # Set column names as patient IDs
  colnames(mtx.expression) <- mtx$merged.dat$bcr 
  # Set row names as probe IDs
  rownames(mtx.expression) <- colnames(mtx$merged.dat)[ 4:ncol(mtx$merged.dat) ] 
  # Save gzipped matrix
  fileName.gz <- gzfile(paste0(results_dir, "/mtx_", disease, "_", data.type, "_", type, "_1expression.txt.gz"), "w")
  write.table(mtx.expression, fileName.gz, sep = ";", quote = FALSE)
  close(fileName.gz)
}
make_mapping_matrix <- function(mtx = mtx, disease = cancer, data.type = data.type, type = type, results_dir = results_dir) {
  mtx.mapping <- data.frame(probeID = colnames(mtx$merged.dat)[ 4:ncol(mtx$merged.dat) ],
                            geneID = colnames(mtx$merged.dat)[ 4:ncol(mtx$merged.dat) ])
  # Save gzipped matrix
  fileName.gz <- gzfile(paste0(results_dir, "/mtx_", disease, "_", data.type, "_", type, "_2mapping.txt.gz"), "w")
  write.table(mtx.mapping, fileName.gz, sep = ";", quote = FALSE, col.names = FALSE, row.names = FALSE)
  close(fileName.gz)
}
make_annotation_matrix <- function(mtx = mtx, disease = cancer, data.type = data.type, type = type, clinical_annotations = clinical_annotations, results_dir = results_dir) {
  mtx.sample <- mtx$merged.dat[, c("bcr", "OS", "status")] # First 3 columns are c("sample_id", "surv_time", "dead_1_alive_0")
  colnames(mtx.sample) <- c("sample_id", "surv_time", "dead_1_alive_0")
  # Append selected clinical annotations
  mtx.sample <- left_join(mtx.sample, data.frame(sample_id = rownames(mtx$clinical), mtx$clinical[, colnames(mtx$clinical) %in% clinical_annotations], stringsAsFactors = FALSE), by = "sample_id")
  mtx.sample[ is.na(mtx.sample) ] <- "N/A"
  mtx.sample <- mtx.sample[, apply(mtx.sample, 2, function(x) length(x[ x != "N/A"])) > 40] # Keep clinical annitations with at least 40 patients
  # Save gzipped matrix
  fileName.gz <- gzfile(paste0(results_dir, "/mtx_", disease, "_", data.type, "_", type, "_3sample.txt.gz"), "w")
  write.table(mtx.sample, fileName.gz, sep = ";", quote = FALSE, row.names = FALSE)
  close(fileName.gz)
}
# mtx <- load_data(disease = cancer, data.type = data.type, type = type, data_dir = data_dir, force_reload = FALSE)

# clinical_annotations <- summarize_data(mtx = mtx)

# make_expression_matrix(mtx = mtx, disease = cancer, data.type = data.type, type = type, results_dir = results_dir)

# make_mapping_matrix(mtx = mtx, disease = cancer, data.type = data.type, type = type, results_dir = results_dir)

# make_annotation_matrix(mtx = mtx, disease = cancer, data.type = data.type, type = type, clinical_annotations = clinical_annotations, results_dir = results_dir)

# Get data for all cancers
get_data <- function(cancers, data.type = data.type, type = type, data_dir = data_dir, force_reload) {
  for (cancer in cancers) {
    print(paste0("Processing cancer ", cancer))
    mtx <- load_data(disease = cancer, data.type = data.type, type = type, data_dir = data_dir, force_reload)
    clinical_annotations <- summarize_data(mtx = mtx)
    make_expression_matrix(mtx = mtx, disease = cancer, data.type = data.type, type = type, results_dir = results_dir)
    make_mapping_matrix(mtx = mtx, disease = cancer, data.type = data.type, type = type, results_dir = results_dir)
    make_annotation_matrix(mtx = mtx, disease = cancer, data.type = data.type, type = type, clinical_annotations = clinical_annotations, results_dir = results_dir)
    rm(list = c("mtx", "clinical_annotations"))
  }
}

# All cancers with RNASeq2 data
data.type = "RNASeq2"; type = "" 
cancer_TCGA = c("ACC", "BLCA", "BRCA", "CESC", "CHOL", "COAD", "COADREAD", "DLBC", "ESCA", "GBM", "GBMLGG", "HNSC", "KICH", "KIPAN", "KIRC", "KIRP", "LAML", "LGG", "LIHC", "LUAD", "LUSC", "MESO", "OV", "PAAD", "PCPG", "PRAD", "READ", "SARC", "SKCM", "STAD", "TGCT", "THCA", "THYM", "UCEC", "UCS")
# All cancers with miRNAseq data. Uncomment to get miRNAseq data
# data.type = "miRNASeq"; type = "rpmmm"
# cancer_TCGA = c("ACC", "BLCA", "BRCA", "CESC", "CHOL", "COAD", "COADREAD", "DLBC", "ESCA", "GBM", "GBMLGG", "HNSC", "KICH", "KIPAN", "KIRC", "KIRP", "LGG", "LIHC", "LUAD", "LUSC", "MESO", "OV", "PAAD", "PCPG", "PRAD", "READ", "SARC", "SKCM", "STAD", "TGCT", "THCA", "THYM", "UCEC", "UCS") # "LAML"

# sink("TCGA2SynTarget.txt", split = FALSE)
get_data(cancers = cancer_TCGA, data.type = data.type, type = type, data_dir = data_dir, force_reload = TRUE)
# sink(type = "message")
# sink()

# Cleanup intermediate files
unlink(paste0(data_dir, "/*.txt.gz"))

# Get number of subjects for all cancers
# All cancers
all_cancers = c("ACC", "BLCA", "BRCA", "CESC", "CHOL", "COAD", "COADREAD", "DLBC", "ESCA", "GBM", "HNSC", "KICH", "KIPAN", "KIRC", "KIRP", "LIHC", "LUAD", "LUSC", "MESO", "OV", "PAAD", "PCPG", "PRAD", "READ", "SARC", "SKCM", "STAD", "TGCT", "THCA", "THYM", "UCEC", "UCS", "GBMLGG", "LGG")
data.type = "RNASeq2"; type = "" 
cancer_counts = rbind()
for (cancer_type in all_cancers) {
  print(paste0("Processing cancer ", cancer_type))
  mtx <- load_data(disease = cancer_type, data.type = data.type, type = type, data_dir = data_dir, force_reload = FALSE)
  # Prepare expression data
  expr <- mtx$merged.dat[ , 4:ncol(mtx$merged.dat)] %>% as.matrix
  cancer_counts <- rbind(cancer_counts, c(cancer_type, nrow(expr)))
}  
cancer_counts <- data.frame(Cancer = cancer_counts[, 1], Samples = as.numeric(cancer_counts[, 2]))
cancer_counts <- cancer_counts[order(cancer_counts$Samples, decreasing = TRUE), ]
write.table(cancer_counts, "data.TCGA/TCGA_cancer_counts.csv", sep = ",", row.names = FALSE, quote = FALSE)
------------------------------------------------------------------------------------------------------------------------
Error
[1] "Processing cancer ACC"
Error: TAR is not installed in the system. Data unzip failed.

[1] "Dimensions of expression matrix, genex X patients: "
[1] "Dimensions of clinical matrix, patients X parameters: "
[1] "Dimensions of merged matrix, patients X parameters + genes: "
[1] "Head of the merged matrix"
NULL
[1] "Head of the clinical matrix"
NULL
[1] "List of clinical values, and frequency of each variable: "
Error during wrapup: dim(X) must have a positive length
Browse[1]> 
Seperate tabs have oppened  apply and stop
---------------------------------------------------------------------------------------------------------------------------------------------
apply tab
function (X, MARGIN, FUN, ...) 
{
  FUN <- match.fun(FUN)
  dl <- length(dim(X))
  if (!dl) 
    stop("dim(X) must have a positive length")
  if (is.object(X)) 
    X <- if (dl == 2L) 
      as.matrix(X)
    else as.array(X)
  d <- dim(X)
  dn <- dimnames(X)
  ds <- seq_len(dl)
  if (is.character(MARGIN)) {
    if (is.null(dnn <- names(dn))) 
      stop("'X' must have named dimnames")
    MARGIN <- match(MARGIN, dnn)
    if (anyNA(MARGIN)) 
      stop("not all elements of 'MARGIN' are names of dimensions")
  }
  s.call <- ds[-MARGIN]
  s.ans <- ds[MARGIN]
  d.call <- d[-MARGIN]
  d.ans <- d[MARGIN]
  dn.call <- dn[-MARGIN]
  dn.ans <- dn[MARGIN]
  d2 <- prod(d.ans)
  if (d2 == 0L) {
    newX <- array(vector(typeof(X), 1L), dim = c(prod(d.call), 
      1L))
    ans <- forceAndCall(1, FUN, if (length(d.call) < 2L) newX[, 
      1] else array(newX[, 1L], d.call, dn.call), ...)
    return(if (is.null(ans)) ans else if (length(d.ans) < 
      2L) ans[1L][-1L] else array(ans, d.ans, dn.ans))
  }
  newX <- aperm(X, c(s.call, s.ans))
  dim(newX) <- c(prod(d.call), d2)
  ans <- vector("list", d2)
  if (length(d.call) < 2L) {
    if (length(dn.call)) 
      dimnames(newX) <- c(dn.call, list(NULL))
    for (i in 1L:d2) {
      tmp <- forceAndCall(1, FUN, newX[, i], ...)
      if (!is.null(tmp)) 
        ans[[i]] <- tmp
    }
  }
  else for (i in 1L:d2) {
    tmp <- forceAndCall(1, FUN, array(newX[, i], d.call, 
      dn.call), ...)
    if (!is.null(tmp)) 
      ans[[i]] <- tmp
  }
  ans.list <- is.recursive(ans[[1L]])
  l.ans <- length(ans[[1L]])
  ans.names <- names(ans[[1L]])
  if (!ans.list) 
    ans.list <- any(lengths(ans) != l.ans)
  if (!ans.list && length(ans.names)) {
    all.same <- vapply(ans, function(x) identical(names(x), 
      ans.names), NA)
    if (!all(all.same)) 
      ans.names <- NULL
  }
  len.a <- if (ans.list) 
    d2
  else length(ans <- unlist(ans, recursive = FALSE))
  if (length(MARGIN) == 1L && len.a == d2) {
    names(ans) <- if (length(dn.ans[[1L]])) 
      dn.ans[[1L]]
    ans
  }
  else if (len.a == d2) 
    array(ans, d.ans, dn.ans)
  else if (len.a && len.a%%d2 == 0L) {
    if (is.null(dn.ans)) 
      dn.ans <- vector(mode = "list", length(d.ans))
    dn1 <- list(ans.names)
    if (length(dn.call) && !is.null(n1 <- names(dn <- dn.call[1])) && 
      nzchar(n1) && length(ans.names) == length(dn[[1]])) 
      names(dn1) <- n1
    dn.ans <- c(dn1, dn.ans)
    array(ans, c(len.a%/%d2, d.ans), if (!is.null(names(dn.ans)) || 
      !all(vapply(dn.ans, is.null, NA))) 
      dn.ans)
  }
  else ans
}
--------------------------------------------------------------------------------------------------------------------------------------------
Stop tab
function (..., call. = TRUE, domain = NULL) 
{
  args <- list(...)
  if (length(args) == 1L && inherits(args[[1L]], "condition")) {
    cond <- args[[1L]]
    if (nargs() > 1L) 
      warning("additional arguments ignored in stop()")
    message <- conditionMessage(cond)
    call <- conditionCall(cond)
    .Internal(.signalCondition(cond, message, call))
    .Internal(.dfltStop(message, call))
  }
  else .Internal(stop(call., .makeMessage(..., domain = domain)))
}
Please let me know if something is not clear, 
1)  I have not downloaded any other data.
2) Two separate tabs opened while running the code apply and stop. I have attached the code within those tabs above for your reference. 
Please let me know how to fix this. Eagerly awaiting your response.
Thanks a lot.

**Comment by mdozmorov** [comment]
> TAR is not installed in the system

You'll need to install tar and make sure it is accessible in the command line.

**Comment by ksrinivasprabhu1999** [comment]
Hi, Thanks. I am running it in on Windows. Is there a way to make it work ? 
How do I install and make it accessible ?

**Comment by mdozmorov** [comment]
There are multiple ways. Suggesting Googling and trying. I don't have Windows, cannot provide more details. Closing this as a non-repository issue.

**Comment by ksrinivasprabhu1999** [comment]
Thanks.

**Comment by ksrinivasprabhu1999** [comment]
Hi does this require me to download any Datatasets prior to running the
script? If so, could you give an example of which and where do I
download it from for TCGA_expression file? Thank you.
Regards,
Prabhum
