### ISSUE TITLE
Am I required to download some data prior to running the script ? 

### ISSUE THREAD

**Issue by ksrinivasprabhu1999** [mdozmorov/TCGAsurvival#8]

**Comment by ksrinivasprabhu1999** [comment]
Hi does this require me to download any Datatasets prior to running the
script? If so, could you give an example of which and where do I
download it from for TCGA_expression analysis script? Thank you.
Regards,
Prabhu

**Comment by mdozmorov** [comment]
https://github.com/mdozmorov/TCGAsurvival#data-preparation
